# def find_a_sum(A):
# 	n = len(A)
# 	A_sum = sum(A)
# 	left_sum = 0
# 	for i in range(n):
# 		left_sum += A[i]
# 		A_sum -= A[i]
# 		if left_sum == A_sum:
# 			return i
# 	return -1
#
#
# A = [1, 2, 3]
# B = [10, 5, 7, 0, 6, 2, 14]
# C = [1, 2, 3, 1, 2]
# print(find_a_sum(A))
# print("lokl")
# print(find_a_sum(B))
# print(find_a_sum(C))


data = """
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H120.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB982H33.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\DB872H83.PAT
<INSTALL_PATH>\LIBRARY DATA\PAT\MOTOROLA_PMP430_17DBI.PAT
"""

import re
import csv


import pandas as pd

# Find all filenames in the given data
filenames = re.findall(r'\\([^\\]+)\.PAT', data)
csv_file_path = 'filenames.csv'

with open(csv_file_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Filename"])  # Write the header
    for filename in filenames:
        writer.writerow([filename])


